version: "3"

services:
  web:
    container_name: web
    image: nginx
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app

  php:
    container_name: php
    build: ./
    expose:
      - 9000
    volumes:
      - ./:/app

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-api}
      # @todo change the password in production
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
      - POSTGRES_USER=${POSTGRES_USER:-mono}
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8877:8080"



